todo/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from todoapp import urls

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include(urls, namespace="todo"))
]

todoapp/urls.py
from django.conf.urls import url
from django.contrib.auth.views import logout


from views import todo_create, login_user, todo_list, todo_update,todo_filter, register_user

urlpatterns = [
    url(r'^todo/$', todo_create, name="index"),
    url(r'^login/$', login_user, name="login"),
    url(r'^logout/$', logout, {'next_page': '/login/'}),
    url(r'^todo_list/$', todo_list, name="todo_list"),
    url(r'^register/$', register_user, name="todo_list"),
    url(r'^todo_filter/$', todo_filter, name="todo_filter"),
    url(r'^(?P<id>[0-9]+)/update/$', todo_update, name='update'),





]

todoapp/models.py
from __future__ import unicode_literals

from django.db import models


class Todo(models.Model):
    name = models.CharField(max_length=100, blank=True)
    description = models.CharField(max_length=225, blank=True)
    low = '1'
    Medium = '2'
    High = '3'
    priority_choice = (
        (High, 'High'),
        (low, 'low'),
        (Medium, 'Medium'))
    state_task_choice = (
        ('todo', 'Todo'),
        ('doing', 'Doing'),
        ('done', 'Done'))
    priority = models.CharField(max_length=1, choices=priority_choice,default=Medium)
    state_task = models.CharField(max_length=10, choices=state_task_choice, default='todo')
    due_date = models.DateField()

todoapp/forms.py
from django import forms


from .models import Todo


class TodoForm(forms.ModelForm):

    class Meta:
        model = Todo
        fields = ['id', 'name', 'description', 'priority', 'state_task', 'due_date']

todoapp/views.py
from django.contrib.auth import authenticate,login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.shortcuts import render, HttpResponseRedirect
from django.http import HttpResponse
from datetime import datetime, timedelta

from .models import Todo
from .forms import TodoForm


@login_required
def todo_create(request):
    if request.method == 'POST':
        form = TodoForm(request.POST)
        print form.is_valid()
        print form.errors
        if form.is_valid():
            print "hello"
            name = form.cleaned_data['name']
            print name
            description = form.cleaned_data.get('description')
            print description
            priority = form.cleaned_data.get('priority')
            state_task = form.cleaned_data.get('state_task')
            due_date = form.cleaned_data.get('due_date')
            print due_date
            if name and description and priority and state_task and due_date:
                todo_obj ,created = Todo.objects.get_or_create(
                    name=name,
                    description=description,
                    priority=priority,
                    state_task=state_task,
                    due_date=due_date
                )
                todo_obj.save()
                return HttpResponseRedirect('/todo_list/')
        return HttpResponse('ERROR IN ADDING TASK')
    form = TodoForm()
    return render(request, 'todo.html',{'form':form})


@login_required
def todo_list(request):
    if request.method == 'GET':
        print request.user
        today_date = datetime.today().date()
        todo = Todo.objects.all()
        return render(request,'index.html',{'todo':todo,'today':today_date})


@login_required
def todo_filter(request):
    if request.method == 'GET':
        date = request.GET.get('date')
        type = request.GET.get('type')
        print date, type
        colour_map = {'todo': 'blue',
                  'doing': 'red',
                  'done': 'green',
                  'expired': 'yellow'}
        if date and type == 'day_wise':
            print "in day"
            todo = Todo.objects.filter(due_date=date)
            return render(request,'index.html',{'todo':todo,'color':colour_map})
        elif date and type == 'week':
            search_date = datetime.strptime(date,'%Y-%m-%d')
            day = search_date - timedelta(days=7)
            todo = Todo.objects.filter(due_date__range=(day,date))
            return render(request,'index.html',{'todo':todo,'color':colour_map})
        elif date and type == 'month':
            search_date = datetime.strptime(date,'%Y-%m-%d')
            day = search_date - timedelta(days=7)
            print day
            todo = Todo.objects.filter(due_date__range=(day,date))
            return render(request,'index.html',{'todo':todo,'color':colour_map})
        else:
            return HttpResponse("please enter date and type to filter")


@login_required
def todo_update(request, id=None):
    if request.method == 'POST':
        instance = Todo.objects.get(id=id)
        form = TodoForm(request.POST or None, instance=instance)
        print form.errors
        if form.is_valid():
            name = form.cleaned_data['name']
            description = form.cleaned_data.get('description')
            priority = form.cleaned_data.get('priority')
            state_task = form.cleaned_data.get('state_task')
            due_date = form.cleaned_data.get('due_date')
        if name and description and priority and state_task and due_date:
            todo_obj = Todo.objects.get(id=id)
            todo_obj.name = name
            todo_obj.description=description
            todo_obj.priority=priority
            todo_obj.state_task=state_task
            todo_obj.due_date=due_date
            todo_obj.save()
            return HttpResponseRedirect('/todo_list/')
        return HttpResponse('ERROR IN ADDING TASK')
    instance = Todo.objects.get(id=id)
    form = TodoForm(request.POST or None, instance=instance)
    return render(request, 'todo_update.html',{'form':form})


def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        print username
        password = request.POST.get('password')
        print password
        if username and password:
            user = authenticate(username=username,password=password)
            if user is not None:
                print "authenticated"
                login(request,user)
                return HttpResponseRedirect('/todo_list/')
            else:
                return HttpResponse("username or password doesn't match")
        else:
            return render(request, 'login.html')
    return render(request, 'login.html')


def register_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        email = request.POST.get('email')
        password1 = request.POST.get('password1')
        password2 = request.POST.get('password2')
        if username and email:
            if password1 == password2:
                user = User.objects.create_user(username=username,
                                                email=email,
                                                password=password1)
                user.save()
                return HttpResponseRedirect('/login/')
            return HttpResponse("password don't match")
        return HttpResponse("data is not correct")
    return render(request,'user_registration.html')

templates/base.html
{% load staticfiles %}
<html lang="en">
<head>
    <title>{% block title %}TodoApp{% endblock title %}</title>
    {% block meta%}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    {%endblock meta%}
<style>
    .center_div{
    margin: 0 auto;
    width:80% /* value of your choice which suits your alignment */
    }
.todo
{
background-color:red;
}
.doing
{
background-color:blue;
}
.done
{
background-color:green;
}
</style>
</head>

<body>
<div class="container">
    {%block body_content%}

    {%endblock body_content%}
</div>

</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% load bootstrap %}
{% block title %} Todo list {% endblock title %}
{%block body_content%}
<div class="pull-right">
    <a href='/logout/'><strong>Logout</strong></a>
</div>
<h1>Todo List</h1>
<a href="/todo/">Create Task here</a><br><br>
{%if user.is_authenticated %}

{%endif%}
<div class="row text-center">
    <form method="get" action="/todo_filter/" class="form-inline">
        Enter date to Filter task<input type="date" name="date" value="date">
            <div class="radio">
                <label><input type="radio" name="type" value="day_wise">day_wise</label>
            </div>
        <div class="radio">
            <label><input type="radio" name="type" value="week">week</label>
        </div>
        <div class="radio">
            <label><input type="radio" name="type" value="month">month</label>
        </div>
        <input type="submit" value="Submit" />
    </form>
    {% for item in todo %}
    <div class="col-sm-4 ">
        <div class="thumbnail {{item.state_task}}" style="">
            <a href="{%url 'todo:update' id=item.id%}">Edit task</a>
            <p><strong>name :{{item.name}}</strong></p>
            <p>Description :{{item.description}}</p>
            <p>Priority :{{item.priority}}</p>
            <p class="{{item.state_task}}">State of task :{{item.state_task}}</p>
            <p>Due Date: {{item.due_date}}</p>
        </div>
    </div>
    {%endfor%}
    </div>

{%endblock body_content%}

templates/login.html
{% extends 'base.html' %}
{% load bootstrap %}
{% block title %} Todo Login {% endblock title %}
{%block body_content%}
    <h1>Login</h1>
    <form action="." method="post" >
    <form class="form-horizontal"method="post" action=".">

        <div class="form-group">
            {%csrf_token%}
            <label class="control-label col-sm-2" for="username">Username</label>
            <div class="col-sm-10">
                <input type="username" class="form-control" id="username" name="username" placeholder="Enter username">
            </div>
        </div>
        <br><br>
        <div class="form-group">
            <label class="control-label col-sm-2">Password</label>
            <div class="col-sm-10">
                <input type="password" class="form-control"  name="password" placeholder="Enter password">
            </div>
        </div>
        <br><br>
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" class="btn btn-default">Submit</button><br><br>
                Not a Member<a href="/register/">Regiter here</a>

            </div>
        </div>
    </form>


        {%endblock body_content%}

templates/todo.html
{% extends 'base.html' %}
{% load bootstrap %}
{% block title %} Create Task {% endblock title %}
{%block body_content%}
{%if user.is_authenticated %}
<div class="pull-right">
<a href='/logout/'><strong>Logout</strong></a>
    </div>
{%endif%}
<h1>Create Task here</h1>
<div class="container center_div">
<form action="/todo/" method="post">
    {% csrf_token %}
    {{ form|bootstrap }}
    <input type="submit" value="Submit" />
</form>
    </div>
{%endblock body_content%}

templates/todo_update.html
{% extends 'base.html' %}
{% load bootstrap %}
{% block title %} Edit Task {% endblock title %}
{%block body_content%}
{%if user.is_authenticated %}
<div class="pull-right">
<a href='/logout/'><strong>Logout</strong></a>
</div>
{%endif%}
<h1>Edit Task here</h1>
<div class="container center_div">
    <form action="." method="post">
        {% csrf_token %}
        {{ form|bootstrap }}
        <input type="submit" value="Submit" />
    </form>
</div>
{%endblock body_content%}

templates/user_registration.html
{% extends 'base.html' %}
{% load bootstrap %}
{% block title %} Todo list {% endblock title %}
{%block body_content%}
<h1>Signup</h1>
    <form class="form-horizontal"method="post" action=".">
        {% csrf_token %}
        <div class="form-group">
            <label class="control-label col-sm-2" for="email">Email:</label>
            <div class="col-sm-10">
                <input type="email" class="form-control" id="email" name="email" placeholder="Enter email">
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-sm-2" for="username">Username</label>
            <div class="col-sm-10">
                <input type="username" class="form-control" id="username" name="username" placeholder="Enter username">
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-sm-2">Password</label>
        <div class="col-sm-10">
            <input type="password" class="form-control"  name="password1" placeholder="Enter password">
        </div>
</div>
    <div class="form-group">
        <label class="control-label col-sm-2" for="pwd">Confirm Password</label>
        <div class="col-sm-10">
            <input type="password" class="form-control" id="pwd" name="password2" placeholder="Enter password again">
        </div>
    </div>
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" class="btn btn-default">Submit</button><br><br>
                Already a Member<a href="#/login">Login here</a>

            </div>
        </div>
    </form>

{%endblock body_content%}